name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js v24
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run oxlint & oxfmt
        run: pnpm lint

  UnitTests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js v24
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm test

  Building:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js v24
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Code
        run: pnpm build
